export const STASHMAPS_BASE_URL =
  import.meta.env.VITE_STASHMAPS_BASE_URL ?? 'https://tiles.internal.windboard.io'

/** Builds the XYZ tile URL template react-leaflet's <TileLayer> expects. */
export function stashmapsTileUrl(farmSlug: string): string {
  return `${STASHMAPS_BASE_URL}/${farmSlug}/{z}/{x}/{y}.png`
}

/** Falls back to a farm-agnostic "world" tileset when no specific farm is selected. */
export const STASHMAPS_DEFAULT_TILE_URL = stashmapsTileUrl('world')

export const STASHMAPS_ATTRIBUTION =
  '&copy; WindBoard — tiles generated by stashmaps'

/** Slugifies a farm display name to match the folder naming stashmaps uses on build. */
export function toFarmSlug(farmName: string): string {
  return farmName.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
}